import {
	type Connection,
	Server,
	type WSMessage,
	routePartykitRequest,
} from "partyserver";

import type { ChatMessage, Message } from "../shared";

export class Chat extends Server<Env> {
	static options = { hibernate: true };

	messages = [] as ChatMessage[];

	broadcastMessage(message: Message, exclude?: string[]) {
		this.broadcast(JSON.stringify(message), exclude);
	}

	async onStart() {
		// this is where you can initialize things that need to be done before the server starts
		// for example, load previous messages from a database or a service

		// We no longer create the table here, it's created in the global fetch handler
		// load the messages from the D1 database
		const { results } = await this.env.DB.prepare(`SELECT * FROM messages`).all();
		this.messages = results as ChatMessage[];
	}

	onConnect(connection: Connection) {
		connection.send(
			JSON.stringify({
				type: "all",
				messages: this.messages,
			} satisfies Message),
		);
	}

	async saveMessage(message: ChatMessage) {
		// check if the message already exists
		const existingMessage = this.messages.find((m) => m.id === message.id);
		if (existingMessage) {
			this.messages = this.messages.map((m) => {
				if (m.id === message.id) {
					return message;
				}
				return m;
			});
		} else {
			this.messages.push(message);
		}

		// Use parameterized queries to prevent SQL injection in D1
		await this.env.DB.prepare(
			`INSERT INTO messages (id, user, role, content) VALUES (?1, ?2, ?3, ?4)
			 ON CONFLICT (id) DO UPDATE SET content = ?5`
		).bind(
			message.id,
			message.user,
			message.role,
			message.content,
			message.content
		).run();
	}

	async onMessage(connection: Connection, message: WSMessage) {
		// let's broadcast the raw message to everyone else
		this.broadcast(message);

		// let's update our local messages store
		const parsed = JSON.parse(message as string) as Message;
		if (parsed.type === "add" || parsed.type === "update") {
			await this.saveMessage(parsed);
		}
	}
}

export default {
	async fetch(request, env) {
		// Initialize D1 database tables if they don't exist
		await env.DB.prepare(
			`CREATE TABLE IF NOT EXISTS messages (id TEXT PRIMARY KEY, user TEXT, role TEXT, content TEXT)`
		).run();
		await env.DB.prepare(
			`CREATE TABLE IF NOT EXISTS users (id TEXT PRIMARY KEY, password_hash TEXT)`
		).run();

		// Insert hardcoded users (sai and rups)
		// We use hashes generated by crypto.createHash('sha256').update(password).digest('hex')
		// saipass -> f844a7fd773d7dc903571b83ccde62eabe3feceebe1ce2eb0c0d7ad18562dc44
		// rupspass -> 230695c9f0b66ff7a82e6cc76cb91295ba2f33c29edf5e250335347b236b1369
		await env.DB.prepare(
			`INSERT INTO users (id, password_hash) VALUES ('sai', 'f844a7fd773d7dc903571b83ccde62eabe3feceebe1ce2eb0c0d7ad18562dc44') ON CONFLICT(id) DO NOTHING`
		).run();
		await env.DB.prepare(
			`INSERT INTO users (id, password_hash) VALUES ('rups', '230695c9f0b66ff7a82e6cc76cb91295ba2f33c29edf5e250335347b236b1369') ON CONFLICT(id) DO NOTHING`
		).run();

		const url = new URL(request.url);

		if (request.method === "POST" && url.pathname === "/api/login") {
			try {
				const { id, password } = await request.json() as any;

				if (!id || !password) {
					return new Response(JSON.stringify({ error: "Missing id or password" }), { status: 400 });
				}

				// Hash the password using Web Crypto API
				const encoder = new TextEncoder();
				const data = encoder.encode(password);
				const hashBuffer = await crypto.subtle.digest('SHA-256', data);
				const hashArray = Array.from(new Uint8Array(hashBuffer));
				const hashHex = hashArray.map(b => b.toString(16).padStart(2, '0')).join('');

				const user = await env.DB.prepare(
					`SELECT id FROM users WHERE id = ?1 AND password_hash = ?2`
				).bind(id, hashHex).first();

				if (user) {
					return new Response(JSON.stringify({ success: true, id }), {
						headers: { "Content-Type": "application/json" }
					});
				} else {
					return new Response(JSON.stringify({ success: false, error: "Invalid credentials" }), {
						status: 401,
						headers: { "Content-Type": "application/json" }
					});
				}
			} catch (e) {
				return new Response(JSON.stringify({ error: "Bad request" }), { status: 400 });
			}
		}

		return (
			(await routePartykitRequest(request, { ...env })) ||
			env.ASSETS.fetch(request)
		);
	},
} satisfies ExportedHandler<Env>;
